### ISSUE TITLE
The cyber theme lacks image resources of waveshare144lcd

### ISSUE THREAD

**Issue by LuckyFishGeek** [V0r-T3x/fancygotchi#1]
Request to add cyber theme image resources adapted to waveshare144lcd

**Comment by V0r-T3x** [comment]
Yeah, the customs themes are only working with a display hat mini as mentioned in the Readme. This is a work in progress actually.

And the defaults themes are more for working example than cool themes.

This will be available soon.

**Comment by LuckyFishGeek** [comment]
Great work, looking forward to it!

Is it mainly developed based on the diplay mini hat screen? I didn't find this screen for sale in my country, only the waveshare 1.44lcd, I wonder if there is a replacement for the diplay mini hat in waveshare!

**Comment by V0r-T3x** [comment]
Sorry, I missed your last comment. I don't know an equivalences for the Display Hat Mini from waveshare or other brand. I'm actually doing some searches on the different resolutions of all compatibles display actually available for the pwnagotchi.

![Screenshot_2023-08-05_112954.png](https://github.com/V0r-T3x/fancygotchi/assets/70115207/e60d18aa-ab26-40cd-a9bd-c234ed05261a)

I'm adjusting some features to make them more compatibles when they are combined, I'm testing it by trying to make themes compatible with all thoses display (with horizontal and vertical themes). All of it's a bigger job than I thought at first.

**Comment by LuckyFishGeek** [comment]
This would be a great piece .
