### ISSUE TITLE
No text on screen, only the images

### ISSUE THREAD

**Issue by lorenzoPrimi** [V0r-T3x/Fancygotchi#17]
**Pwnagotchi Version**: ``Last image on their github``
**Screen Type**: ``Waveshare_v3``

**Describe the bug**
Any theme I select has no text, I only see the images. (In my case Pikachu)
Using PWNACHU, but I tried them all.

**Logs**
```
[2024-12-06 10:12:42,306] [INFO] [Fancygotchi] Error while rgba_text (; <PIL.ImageFont.FreeTypeFont object at 0xb096b2d0>; black; 250; 122): 'FreeTypeFont' object has no attribute 'getbbox'
[2024-12-06 10:12:42,310] [INFO] [Fancygotchi] Traceback (most recent call last):
  File "/usr/local/share/pwnagotchi/installed-plugins/Fancygotchi.py", line 4903, in rgba_text
    _,_,w,h = tfont.getbbox(text)
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
```

**Comment by V0r-T3x** [comment]
Which pwnagotchi version are you using? And which repo? 1.8.5? 2.8.5...?

jayofelone? Aluminium-ice?

The fix for the newer PIL version is surely causing trouble with the older pwnagotchi version.

Or if you can give me the PIL Version this can help me for the test and fix.

**Comment by lorenzoPrimi** [comment]
Wait is there anything new after 1.5.5? I thought that was the last release!
I'm using 1.5.5, if there is a new release let me know and I can update it.

**Comment by V0r-T3x** [comment]
The community released updated images. Jayofelony has a version for 32bit and 64bit.

You can check our community website, there is good information to start with this project.

https://pwnagotchi.org/3rd-party-images/index.html

**Comment by lorenzoPrimi** [comment]
Thanks, I had no idea there were newer versions available. I installed the Jayofelony image and everything worked smoothly.
I agree that might be good to have retro-compatibility if it's a quick fix!

**Comment by V0r-T3x** [comment]
I just updated the main branch with the retro-compatibility fix. I tried it on the 1.5.5 and its working well. Thanks for you issue call.

**Comment by lorenzoPrimi** [comment]
Thanks to you for helping me discovery the new Pwnagotchi version!
