### ISSUE TITLE
Some conflicts in README

### ISSUE THREAD

**Issue by amenekowo** [V0r-T3x/fancygotchi#7]
Hi! I just noticed something conflict in readme:
- v.2023.09.1 Fix for compatibility problem of aluminum-ice 1.7.8+ and xbits 2.2.9+
- FANCYGOTCHI IS NOT COMPATIBLE WITH: ALUMINUM-ICE 1.7.8 AND LATER

So is it or isn't compatible with Aluminum-ice's fork? Just wondered because I'm going to upgrade to the latest version.
Thank your hard work for making this plugin by the way!

**Comment by V0r-T3x** [comment]
Ok I will check the infos in the README. The last release should be compatible with the new images of xbits and aluminum-ice. I'm actually coding my code again in a better way, and this should be help the future compatibility.
