### ISSUE TITLE
Bug with a repo that uses Fancygotchi with checking for updates

### ISSUE THREAD

**Issue by avipars** [V0r-T3x/Fancygotchi#9]
For users that have this as a plugin repo: 
https://github.com/itsdarklikehell/pwnagotchi-plugins/archive/master.zip

When they try to run 

pwnagotchi plugins update 

and/or 

pwnagotchi plugins list

They will see this:

![image](https://github.com/user-attachments/assets/4c42db1f-ca26-4ffd-ad7d-3e745ae8ecfc)

As the code relies upon a specific file in your repo to be there
![image](https://github.com/user-attachments/assets/75a32485-3f82-4c44-92a4-fa633603cadd)

https://github.com/itsdarklikehell/pwnagotchi-plugins/blob/master/fancygotchi.py

Potential solution: have the URL that the function is expecting return something other than a 404 error?

**Comment by V0r-T3x** [comment]
There will never be an update from any of this old code. So nothing to change...
